import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{LineChart,Line,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell}from'recharts';
import{Sprout,LayoutDashboard,Warehouse,Leaf,Hotel,Truck,Wallet,Beaker,Package,BarChart3,Bot,ShoppingCart,CalendarCheck,CheckCircle2}from'lucide-react';
import'./style.css';

const fmt=n=>new Intl.NumberFormat('en-TZ',{maximumFractionDigits:0}).format(n);
const usd=n=>'$'+new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
const tzs=n=>'TZS '+fmt(n);

const crops=[
 {name:'Lettuce heads',system:'NFT',plants:120,days:42,weekly:20,unit:'head',price:2500,cost:650,quality:4.7},
 {name:'Chef salad bags',system:'NFT',plants:70,days:35,weekly:24,unit:'200g bag',price:6000,cost:1700,quality:4.8},
 {name:'Rocket',system:'NFT',plants:40,days:35,weekly:8,unit:'200g bag',price:6500,cost:1500,quality:4.5},
 {name:'Genovese basil',system:'NFT',plants:40,days:45,weekly:8,unit:'bunch',price:3000,cost:750,quality:4.6},
 {name:'Mini cucumber',system:'Dutch bucket',plants:12,days:50,weekly:18,unit:'fruit',price:1500,cost:450,quality:4.4}
];
const channels=Array.from({length:12},(_,i)=>({id:`NFT-${String(i+1).padStart(2,'0')}`,crop:i<5?'Lettuce':i<8?'Salad mix':i<10?'Rocket':'Basil',age:[7,14,21,28,35,12,19,26,9,16,23,30][i],sites:20,health:[98,96,94,92,90,97,95,93,99,96,94,91][i]}));
const hotels=[
 {name:'Friend Hotel A',type:'6 villas / 30 guests max',weekly:170000,orders:'20 lettuce, 10 salad bags, 6 basil',paid:'Good',next:'Monday'},
 {name:'Friend Hotel B',type:'40 guests max',weekly:260000,orders:'25 salad bags, 10 rocket, cucumbers',paid:'Sample stage',next:'Thursday'}
];
const equipment=[
 ['NFT channel 100x50mm',48,'m',7096,340608,'High'],['End caps',24,'pcs',4500,108000,'High'],['500L food-grade tank',1,'unit',350000,350000,'High'],['Pump 3000-4000 L/h',1,'unit',180000,180000,'High'],['PVC plumbing/fittings',1,'lot',300000,300000,'High'],['Steel frame',1,'lot',900000,900000,'High'],['50mm net pots',240,'pcs',700,168000,'High'],['Seed trays',5,'pcs',18000,90000,'High'],['pH meter',1,'unit',150000,150000,'High'],['EC meter',1,'unit',150000,150000,'High'],['Nutrients A+B',1,'set',250000,250000,'High'],['Packaging start stock',1,'lot',150000,150000,'Medium']
];
const sales=[{week:'W1',revenue:180000,cost:65000},{week:'W2',revenue:280000,cost:94000},{week:'W3',revenue:410000,cost:132000},{week:'W4',revenue:520000,cost:165000}];
const logs=[{date:'Today',ph:6.1,ec:1.45,temp:28,note:'Good for lettuce/herbs'},{date:'Yesterday',ph:6.3,ec:1.35,temp:29,note:'Add small nutrients'},{date:'Tue',ph:5.9,ec:1.42,temp:28,note:'Stable'}];

function Sidebar({page,setPage}){const items=[['Dashboard',LayoutDashboard],['Farm map',Warehouse],['Crops',Leaf],['Harvest planner',CalendarCheck],['Hotels',Hotel],['Deliveries',Truck],['Financials',Wallet],['Hydroponics',Beaker],['Inventory',Package],['Procurement',ShoppingCart],['Analytics',BarChart3],['AI Planner',Bot]];return <aside className="sidebar"><div className="brand"><div className="logo"><Sprout size={22}/></div><div><b>Zanzibar Fresh OS</b><span>Prototype farm command center</span></div></div><nav>{items.map(([n,Icon])=><button key={n} onClick={()=>setPage(n)} className={page===n?'active':''}><Icon size={18}/>{n}</button>)}</nav></aside>}
function Card({title,children,wide}){return <section className={wide?'card wide':'card'}><h3>{title}</h3>{children}</section>}
function KPI({label,value,sub}){return <div className="kpi"><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function App(){const[page,setPage]=useState('Dashboard');const monthly=useMemo(()=>crops.reduce((s,c)=>s+c.weekly*c.price*4.33,0),[]);const gross=useMemo(()=>crops.reduce((s,c)=>s+c.weekly*(c.price-c.cost)*4.33,0),[]);const startup=equipment.reduce((s,e)=>s+e[4],0);return <div className="app"><Sidebar page={page} setPage={setPage}/><main><header><div><h1>{page}</h1><p>Premium salad greens, herbs and hotel supply prototype for Zanzibar’s south east coast.</p></div><div className="pill">Prototype: 12 channels / 240 plant sites</div></header>{page==='Dashboard'&&<Dashboard monthly={monthly} gross={gross} startup={startup}/>} {page==='Farm map'&&<Farm/>}{page==='Crops'&&<Crops/>}{page==='Harvest planner'&&<Harvest/>}{page==='Hotels'&&<Hotels/>}{page==='Deliveries'&&<Deliveries/>}{page==='Financials'&&<Financials monthly={monthly} gross={gross} startup={startup}/>} {page==='Hydroponics'&&<Hydro/>}{page==='Inventory'&&<Inventory/>}{page==='Procurement'&&<Procurement startup={startup}/>} {page==='Analytics'&&<Analytics/>}{page==='AI Planner'&&<AI/>}</main></div>}
function Dashboard({monthly,gross,startup}){return <><div className="grid4"><KPI label="Projected revenue" value={tzs(monthly)} sub="monthly at current crop plan"/><KPI label="Projected gross profit" value={tzs(gross)} sub="before labour/depreciation"/><KPI label="Startup budget" value={tzs(startup)} sub="prototype equipment"/><KPI label="Payback" value={(startup/gross).toFixed(1)+' months'} sub="if sales hit projection"/></div><div className="grid"><Card title="Revenue ramp" wide><ResponsiveContainer width="100%" height={260}><LineChart data={sales}><XAxis dataKey="week"/><YAxis/><Tooltip formatter={v=>tzs(v)}/><Line type="monotone" dataKey="revenue" strokeWidth={3}/><Line type="monotone" dataKey="cost" strokeWidth={3}/></LineChart></ResponsiveContainer></Card><Card title="This week"><ul className="tasks"><li><CheckCircle2/> Sow 40 lettuce + 20 rocket</li><li><CheckCircle2/> Check pH and EC morning/evening</li><li><CheckCircle2/> Prepare first hotel sample box</li><li><CheckCircle2/> Confirm basil demand with chefs</li></ul></Card></div></>}
function Farm(){return <div className="grid"><Card title="NFT channel map" wide><div className="channels">{channels.map(c=><div className="channel" key={c.id}><div><b>{c.id}</b><span>{c.crop}</span></div><div className="plants">{Array.from({length:10},(_,i)=><i key={i}/>)}</div><small>{c.age} days old · health {c.health}% · {c.sites} sites</small></div>)}</div></Card><Card title="System status"><KPI label="Plant sites" value="240" sub="12 × 20 sites"/><KPI label="Reservoir" value="500L" sub="target build"/><KPI label="Next expansion" value="24 channels" sub="480 plant sites"/></Card></div>}
function Crops(){return <Card title="Crop products" wide><table><thead><tr><th>Crop</th><th>System</th><th>Plants</th><th>Cycle</th><th>Weekly harvest</th><th>Price</th><th>Gross/week</th></tr></thead><tbody>{crops.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.system}</td><td>{c.plants}</td><td>{c.days} days</td><td>{c.weekly} {c.unit}</td><td>{tzs(c.price)}</td><td>{tzs(c.weekly*(c.price-c.cost))}</td></tr>)}</tbody></table></Card>}
function Harvest(){return <div className="grid"><Card title="Upcoming harvests" wide><table><thead><tr><th>Day</th><th>Harvest</th><th>Pack</th><th>Customer</th></tr></thead><tbody><tr><td>Monday</td><td>20 lettuce, 8 salad bags, 6 basil</td><td>Chef box</td><td>Hotel A samples</td></tr><tr><td>Thursday</td><td>15 salad bags, 8 rocket, cucumbers</td><td>Mixed order</td><td>Hotel B</td></tr><tr><td>Sunday</td><td>Quality check</td><td>Family/home use</td><td>Internal</td></tr></tbody></table></Card><Card title="Sowing rule"><p>For every confirmed weekly order, sow 15–20% extra to cover germination, heat stress and harvest losses.</p></Card></div>}
function Hotels(){return <div className="cards">{hotels.map(h=><Card key={h.name} title={h.name}><p>{h.type}</p><b>{tzs(h.weekly)}/week potential</b><p>{h.orders}</p><span className="pill">Next: {h.next}</span></Card>)}</div>}
function Deliveries(){return <Card title="Delivery planner" wide><table><thead><tr><th>Date</th><th>Customer</th><th>Items</th><th>Status</th></tr></thead><tbody><tr><td>Monday 7am</td><td>Hotel A</td><td>Sample chef box</td><td>Prepare</td></tr><tr><td>Thursday 7am</td><td>Hotel B</td><td>Salad mix + rocket</td><td>Confirm</td></tr></tbody></table></Card>}
function Financials({monthly,gross,startup}){return <div className="grid"><Card title="Financial snapshot"><KPI label="Revenue/month" value={tzs(monthly)} sub={usd(monthly/2600)}/><KPI label="Gross profit/month" value={tzs(gross)} sub={usd(gross/2600)}/><KPI label="Startup cost" value={tzs(startup)} sub={usd(startup/2600)}/></Card><Card title="Revenue by crop" wide><ResponsiveContainer width="100%" height={280}><BarChart data={crops.map(c=>({crop:c.name,revenue:c.weekly*c.price*4.33}))}><XAxis dataKey="crop"/><YAxis/><Tooltip formatter={v=>tzs(v)}/><Bar dataKey="revenue" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card></div>}
function Hydro(){return <div className="grid"><Card title="Reservoir log" wide><table><thead><tr><th>Date</th><th>pH</th><th>EC</th><th>Temp</th><th>Note</th></tr></thead><tbody>{logs.map(l=><tr key={l.date}><td>{l.date}</td><td>{l.ph}</td><td>{l.ec}</td><td>{l.temp}°C</td><td>{l.note}</td></tr>)}</tbody></table></Card><Card title="Targets"><p>Leafy greens: pH 5.8–6.3. EC roughly 1.2–1.8 depending crop age and heat.</p></Card></div>}
function Inventory(){return <Card title="Inventory" wide><table><thead><tr><th>Item</th><th>Stock</th><th>Reorder at</th><th>Status</th></tr></thead><tbody><tr><td>Lettuce seeds</td><td>1 pack</td><td>25%</td><td>OK</td></tr><tr><td>Rocket seeds</td><td>1 pack</td><td>25%</td><td>OK</td></tr><tr><td>Nutrients A+B</td><td>0</td><td>1 set</td><td>Buy</td></tr><tr><td>Salad bags</td><td>0</td><td>100</td><td>Buy</td></tr></tbody></table></Card>}
function Procurement({startup}){return <Card title={`Prototype shopping list · ${tzs(startup)}`} wide><table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>Total</th><th>Priority</th></tr></thead><tbody>{equipment.map(e=><tr key={e[0]}><td>{e[0]}</td><td>{e[1]}</td><td>{e[2]}</td><td>{tzs(e[3])}</td><td>{tzs(e[4])}</td><td>{e[5]}</td></tr>)}</tbody></table></Card>}
function Analytics(){const pie=crops.map(c=>({name:c.name,value:c.weekly*c.price*4.33}));return <div className="grid"><Card title="Revenue mix"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={pie} dataKey="value" nameKey="name" outerRadius={90} label>{pie.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={v=>tzs(v)}/></PieChart></ResponsiveContainer></Card><Card title="Quality scores"><table><tbody>{crops.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.quality}/5</td></tr>)}</tbody></table></Card></div>}
function AI(){return <div className="cards"><Card title="Recommendation"><p>Start with 12 channels but plant only 160–180 sites in the first cycle. Keep spare capacity for mistakes and samples.</p></Card><Card title="Sales focus"><p>Push chef salad bags, lettuce heads and basil first. Treat mini cucumber as a premium trial in Dutch buckets.</p></Card><Card title="Next action"><p>Ask both hotel chefs for weekly quantities and current prices before buying the full 24-channel expansion.</p></Card></div>}

createRoot(document.getElementById('root')).render(<App/>);
