import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{AreaChart,Area,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,LineChart,Line}from'recharts';import{Sprout,LayoutDashboard,Leaf,Hotel,Truck,Wallet,Cpu,Package,ChartNoAxesCombined,Brain,Settings,Plus,Search,Droplets,FlaskConical,CalendarDays,CheckCircle2,AlertTriangle}from'lucide-react';import'./styles.css';
const money=n=>new Intl.NumberFormat('en-US').format(Math.round(n));
const crops=[{name:'Lettuce heads',system:'NFT',cycle:42,plants:240,price:2500,cost:520,unit:'head',stage:'Core crop',health:94},{name:'Chef salad mix',system:'NFT',cycle:30,plants:160,price:5000,cost:1250,unit:'200g bag',stage:'Premium mix',health:91},{name:'Rocket',system:'NFT',cycle:28,plants:120,price:18000,cost:5200,unit:'kg',stage:'High value',health:88},{name:'Genovese basil',system:'NFT',cycle:35,plants:140,price:20000,cost:4700,unit:'kg',stage:'Chef favourite',health:96},{name:'Mini cucumber',system:'Dutch buckets',cycle:55,plants:28,price:3500,cost:950,unit:'piece',stage:'Trial crop',health:84}];
const hotels=[{name:'Kijani Villas',rooms:6,capacity:30,chef:'Amina',order:'24 lettuce, 12 salad bags, 1kg basil',monthly:760000,status:'Sample partner'},{name:'Bahari Boutique',rooms:12,capacity:40,chef:'Marco',order:'36 lettuce, 20 salad bags, 2kg rocket',monthly:1180000,status:'Target account'},{name:'Paje Garden Kitchen',rooms:0,capacity:60,chef:'Lena',order:'Trial: basil + rocket',monthly:320000,status:'Restaurant lead'}];
const channels=Array.from({length:24},(_,i)=>{const crop=crops[i%crops.length];return{id:i+1,crop:crop.name,plants:i%5===4?14:20,age:7+(i*3)%38,health:82+(i*7)%17}});
const deliveries=[{day:'Monday',hotel:'Kijani Villas',items:'18 lettuce, 8 salad bags, basil',value:168000,done:true},{day:'Monday',hotel:'Bahari Boutique',items:'22 lettuce, 10 salad bags, rocket',value:225000,done:false},{day:'Thursday',hotel:'Kijani Villas',items:'6 lettuce, 4 salad bags',value:51000,done:false},{day:'Thursday',hotel:'Bahari Boutique',items:'14 lettuce, 10 salad bags, basil',value:194000,done:false}];
const nutrientLogs=[{date:'Jun 24',ph:6.1,ec:1.4},{date:'Jun 25',ph:6.0,ec:1.5},{date:'Jun 26',ph:5.9,ec:1.6},{date:'Jun 27',ph:6.2,ec:1.5},{date:'Jun 28',ph:6.1,ec:1.7},{date:'Jun 29',ph:6.0,ec:1.6}];
const inventory=[['A+B nutrients','4.5 L','21 days','ok'],['Net pots','220','Enough for expansion','ok'],['Salad bags','180','Order soon','warn'],['Lettuce seed','3 packets','Good','ok'],['pH down','500 ml','Good','ok'],['Coco coir','2 bags','Low','warn']];
function App(){const[page,setPage]=useState('Dashboard');const[ass,setAss]=useState({channels:24,priceBag:5000,priceHead:2500,loss:10,costs:420000});const kpi=useMemo(()=>{let heads=ass.channels*20/6*(1-ass.loss/100);let monthlyRevenue=heads*4.33*ass.priceHead+80*ass.priceBag+520000;return{heads,monthlyRevenue,profit:monthlyRevenue-ass.costs,roi:(monthlyRevenue-ass.costs)*12/3200000*100}},[ass]);const pages={Dashboard:<Dashboard kpi={kpi}/>,Farm:<Farm/>,Crops:<Crops/>,Hotels:<Hotels/>,Deliveries:<Deliveries/>,Financials:<Financials ass={ass} setAss={setAss} kpi={kpi}/>,Hydroponics:<Hydroponics/>,Inventory:<Inventory/>,Analytics:<Analytics/>,AI:<AI kpi={kpi}/>,Settings:<SettingsPage/>};return <div className="app"><aside><div className="brand"><div className="logo"><Sprout size={24}/></div><div><b>Zanzibar Fresh OS</b><span>Premium greens command centre</span></div></div>{Object.keys(pages).map(p=><button className={page===p?'active':''}onClick={()=>setPage(p)} key={p}>{icons[p]}{p}</button>)}</aside><main><header><div><p className="eyebrow">South East Coast • Zanzibar</p><h1>{page}</h1></div><div className="search"><Search size={16}/>Search crops, hotels, deliveries</div></header>{pages[page]}</main></div>}
const icons={Dashboard:<LayoutDashboard/>,Farm:<Sprout/>,Crops:<Leaf/>,Hotels:<Hotel/>,Deliveries:<Truck/>,Financials:<Wallet/>,Hydroponics:<FlaskConical/>,Inventory:<Package/>,Analytics:<ChartNoAxesCombined/>,AI:<Brain/>,Settings:<Settings/>};
function Card({title,children,wide}){return <section className={'card '+(wide?'wide':'')}><h3>{title}</h3>{children}</section>}
function Dashboard({kpi}){const rev=[{m:'Jul',v:900000},{m:'Aug',v:1350000},{m:'Sep',v:1900000},{m:'Oct',v:2600000},{m:'Nov',v:3400000},{m:'Dec',v:4300000}];return <div className="grid"><div className="hero wide"><div><p className="eyebrow">Today’s command brief</p><h2>Harvest, pack, deliver, learn.</h2><p>Your pilot is modelled around 24 NFT channels, 2 hotel partners, premium lettuce, salad bags, rocket, basil and mini cucumbers.</p></div><div className="statBig">TZS {money(kpi.profit)}<span>projected monthly profit</span></div></div><Metric label="Monthly revenue" value={'TZS '+money(kpi.monthlyRevenue)}/><Metric label="Weekly lettuce" value={money(kpi.heads)+' heads'}/><Metric label="Hotels" value="2 active + 1 lead"/><Metric label="ROI run-rate" value={Math.round(kpi.roi)+'%'}/><Card title="Revenue forecast" wide><ResponsiveContainer height={240}><AreaChart data={rev}><XAxis dataKey="m"/><YAxis hide/><Tooltip/><Area dataKey="v" fillOpacity={.25}/></AreaChart></ResponsiveContainer></Card><Card title="Today’s tasks"><ul className="tasks"><li><CheckCircle2/>Check pH and EC before 8am</li><li><CalendarDays/>Sow 42 lettuce for next cycle</li><li><Truck/>Prepare Kijani sample box</li><li><AlertTriangle/>Order more salad bags</li></ul></Card></div>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function Farm(){return <div className="grid"><Card title="NFT channel map" wide><div className="channels">{channels.map(c=><div className="channel" key={c.id}><b>CH {c.id.toString().padStart(2,'0')}</b><span>{c.crop}</span><small>{c.plants} plants • day {c.age}</small><div className="bar"><i style={{width:c.health+'%'}}/></div></div>)}</div></Card><Card title="Farm notes"><p>Use this map as your digital twin. Each channel tracks crop, plant count, age, health and harvest timing.</p></Card></div>}
function Crops(){return <div className="grid">{crops.map(c=><Card title={c.name} key={c.name}><p className="pill">{c.system}</p><h2>{c.plants}</h2><p>Plants growing • {c.cycle} day cycle</p><p>Selling price: <b>TZS {money(c.price)}</b> / {c.unit}</p><p>Estimated unit cost: TZS {money(c.cost)}</p><div className="bar"><i style={{width:c.health+'%'}}/></div></Card>)}</div>}
function Hotels(){return <div className="grid">{hotels.map(h=><Card title={h.name} key={h.name}><p className="pill">{h.status}</p><p>Capacity: {h.capacity} guests</p><p>Chef/contact: <b>{h.chef}</b></p><p>{h.order}</p><h2>TZS {money(h.monthly)}</h2><p>Potential monthly spend</p></Card>)}</div>}
function Deliveries(){return <div className="grid"><Card title="Delivery schedule" wide><table><tbody>{deliveries.map((d,i)=><tr key={i}><td>{d.day}</td><td>{d.hotel}</td><td>{d.items}</td><td>TZS {money(d.value)}</td><td>{d.done?'Packed':'Open'}</td></tr>)}</tbody></table></Card></div>}
function Financials({ass,setAss,kpi}){return <div className="grid"><Card title="Scenario controls"><Label label="NFT channels" v={ass.channels} set={v=>setAss({...ass,channels:+v})}/><Label label="Salad bag price" v={ass.priceBag} set={v=>setAss({...ass,priceBag:+v})}/><Label label="Lettuce head price" v={ass.priceHead} set={v=>setAss({...ass,priceHead:+v})}/><Label label="Harvest loss %" v={ass.loss} set={v=>setAss({...ass,loss:+v})}/><Label label="Monthly costs" v={ass.costs} set={v=>setAss({...ass,costs:+v})}/></Card><Card title="Profit model"><Metric label="Revenue" value={'TZS '+money(kpi.monthlyRevenue)}/><Metric label="Profit" value={'TZS '+money(kpi.profit)}/><Metric label="Payback estimate" value={(3200000/Math.max(kpi.profit,1)).toFixed(1)+' months'}/></Card></div>}
function Label({label,v,set}){return <label><span>{label}</span><input type="number" value={v} onChange={e=>set(e.target.value)}/></label>}
function Hydroponics(){return <div className="grid"><Card title="pH / EC log" wide><ResponsiveContainer height={250}><LineChart data={nutrientLogs}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="ph"/><Line dataKey="ec"/></LineChart></ResponsiveContainer></Card><Metric label="Current pH" value="6.0"/><Metric label="Current EC" value="1.6"/><Metric label="Tank" value="500 L"/></div>}
function Inventory(){return <div className="grid"><Card title="Inventory" wide><table><tbody>{inventory.map((r,i)=><tr key={i}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className={'pill '+r[3]}>{r[3]}</span></td></tr>)}</tbody></table></Card></div>}
function Analytics(){const data=crops.map(c=>({name:c.name,profit:c.price-c.cost}));return <div className="grid"><Card title="Profit per product" wide><ResponsiveContainer height={260}><BarChart data={data}><XAxis dataKey="name"/><YAxis hide/><Tooltip/><Bar dataKey="profit" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card><Card title="Crop mix"><ResponsiveContainer height={230}><PieChart><Pie data={crops} dataKey="plants" nameKey="name" outerRadius={85}>{crops.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Card></div>}
function AI({kpi}){return <div className="grid"><div className="hero wide"><Brain size={36}/><h2>AI grower notes</h2><p>Based on your model, keep lettuce and salad bags as the base revenue, then use basil and rocket as premium margin products.</p></div><Card title="Recommendations"><ul className="tasks"><li><Sprout/>Sow 42 lettuce this week to maintain weekly supply.</li><li><Leaf/>Trial rocket in 4 channels before committing more capacity.</li><li><Wallet/>At current assumptions, projected profit is TZS {money(kpi.profit)} / month.</li><li><Hotel/>Ask both chefs whether they prefer whole heads or 200g washed bags.</li></ul></Card></div>}
function SettingsPage(){return <div className="grid"><Card title="Business profile"><p><b>Zanzibar Fresh</b></p><p>Premium locally grown salad greens, herbs and mini cucumbers for boutique hotels and restaurants.</p></Card><Card title="Next build"><p>Next version should add Supabase login, saved records, invoices, image uploads and mobile offline mode.</p></Card></div>}
createRoot(document.getElementById('root')).render(<App/>);
